server:
  port: 8010
spring:
  application:
    name: microservice-consumer-shopping

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/ ,http://eureka2:8762/eureka/
  instance:
    prefer-ip-address: true

management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true
